In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataframe = pd.read_csv('/content/Churn_Modelling.csv')
dataframe

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
X = dataframe.iloc[:, 3:-1].values
y = dataframe.iloc[:, -1].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [6]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [12]:
print(X_train)

[[0.0 0.0 1.0 ... 0.6425949687704583 -1.032270427743097
  1.1064316603959783]
 [0.0 1.0 0.0 ... 0.6425949687704583 0.9687383975403476
  -0.7486644675354388]
 [1.0 0.0 0.0 ... 0.6425949687704583 -1.032270427743097
  1.4853346670155114]
 ...
 [1.0 0.0 0.0 ... 0.6425949687704583 -1.032270427743097 1.41231993812971]
 [0.0 0.0 1.0 ... 0.6425949687704583 0.9687383975403476
  0.8443212126890052]
 [0.0 1.0 0.0 ... 0.6425949687704583 -1.032270427743097
  0.32472464658797995]]


In [13]:
print(X_test)

[[0.0 1.0 0.0 ... 0.6425949687704583 0.9687383975403476 1.610857068384663]
 [1.0 0.0 0.0 ... 0.6425949687704583 -1.032270427743097 0.495870368799669]
 [0.0 0.0 1.0 ... 0.6425949687704583 0.9687383975403476
  -0.4247867388302741]
 ...
 [0.0 0.0 1.0 ... 0.6425949687704583 -1.032270427743097
  0.7188846723542285]
 [0.0 1.0 0.0 ... 0.6425949687704583 0.9687383975403476
  -1.5450780513082376]
 [0.0 1.0 0.0 ... 0.6425949687704583 -1.032270427743097
  1.6125591677968796]]


In [14]:
ann = tf.keras.models.Sequential()

In [15]:
# Adding input layer and first hidden layer.
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
# Adding second hidden layer.
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [17]:
# Adding output layer
# For non-binary classification, the activation function should be SoftMax
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [18]:
# binary_crossentropy - When you are doing binary classification (binary outcome).
# categorical_crossentropy- Non-binary classification, like predicting 3 different categories
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [19]:
# Training ANN
ann.fit(X_train.astype(np.float32), y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7734 - loss: 0.6057
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7912 - loss: 0.4858
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8117 - loss: 0.4337
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8255 - loss: 0.4055
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8321 - loss: 0.3976
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8336 - loss: 0.3916
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8455 - loss: 0.3684
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8435 - loss: 0.3720
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8460 - loss: 0.3644
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8529 - loss: 0.3537
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8582 - loss: 0.3496
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

## Part 4 - Making the predictions and evaluating the model.

### Predicting the result of a single observation.

**Homework**

Use our ANN model to predict if the costumer with the following information will leave the bank:

- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: 60000
- Number of products: 2
- Does this costumer have a credit card? Yes
- Is this costumer an active member? Yes
- Estimated salary: 50000

So, should we say goodbye to this costumer or no?

In [20]:
# Solution
x_prueba = np.array([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]).astype(np.float32)
x_prueba

array([[1.e+00, 0.e+00, 0.e+00, 6.e+02, 1.e+00, 4.e+01, 3.e+00, 6.e+04,
        2.e+00, 1.e+00, 1.e+00, 5.e+04]], dtype=float32)

In [21]:
x_prueba[:, 3:] = sc.transform(x_prueba[:, 3:])

In [22]:
x_prueba

array([[ 1.        ,  0.        ,  0.        , -0.52111596,  0.91601336,
         0.10961719, -0.68538964, -0.2569057 ,  0.8095029 ,  0.642595  ,
         0.9687384 , -0.8720332 ]], dtype=float32)

In [24]:
print(ann.predict(x_prueba) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[False]]


In [28]:
y_predict = ann.predict(X_test.astype(np.float32))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [30]:
y_predict = (y_predict > 0.5)
y_predict

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [31]:
results = np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)), axis=1)

In [32]:
results

array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_predict, y_test)
print(cm)
accuracy_score(y_predict, y_test)

[[1521  208]
 [  74  197]]


0.859