In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataframe = pd.read_csv('/content/Churn_Modelling.csv')
dataframe

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
X = dataframe.iloc[:, 3:-1].values
y = dataframe.iloc[:, -1].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [6]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [12]:
print(X_train)

[[0.0 0.0 1.0 ... 0.6425949687704583 -1.032270427743097
  1.1064316603959783]
 [0.0 1.0 0.0 ... 0.6425949687704583 0.9687383975403476
  -0.7486644675354388]
 [1.0 0.0 0.0 ... 0.6425949687704583 -1.032270427743097
  1.4853346670155114]
 ...
 [1.0 0.0 0.0 ... 0.6425949687704583 -1.032270427743097 1.41231993812971]
 [0.0 0.0 1.0 ... 0.6425949687704583 0.9687383975403476
  0.8443212126890052]
 [0.0 1.0 0.0 ... 0.6425949687704583 -1.032270427743097
  0.32472464658797995]]


In [13]:
print(X_test)

[[0.0 1.0 0.0 ... 0.6425949687704583 0.9687383975403476 1.610857068384663]
 [1.0 0.0 0.0 ... 0.6425949687704583 -1.032270427743097 0.495870368799669]
 [0.0 0.0 1.0 ... 0.6425949687704583 0.9687383975403476
  -0.4247867388302741]
 ...
 [0.0 0.0 1.0 ... 0.6425949687704583 -1.032270427743097
  0.7188846723542285]
 [0.0 1.0 0.0 ... 0.6425949687704583 0.9687383975403476
  -1.5450780513082376]
 [0.0 1.0 0.0 ... 0.6425949687704583 -1.032270427743097
  1.6125591677968796]]


In [14]:
ann = tf.keras.models.Sequential()

In [15]:
# Adding input layer and first hidden layer.
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
# Adding second hidden layer.
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [17]:
# Adding output layer
# For non-binary classification, the activation function should be SoftMax
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [18]:
# binary_crossentropy - When you are doing binary classification (binary outcome).
# categorical_crossentropy- Non-binary classification, like predicting 3 different categories
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [20]:
# Training ANN
ann.fit(X_train.astype(np.float32), y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6978 - loss: 0.6294
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7962 - loss: 0.4572
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7987 - loss: 0.4312
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8034 - loss: 0.4286
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8018 - loss: 0.4320
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8101 - loss: 0.4220
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8176 - loss: 0.4041
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8119 - loss: 0.4230
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8119 - loss: 0.4081
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8138 - loss: 0.4040
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8168 - loss: 0.4001
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━